---
- name: Cau hinh timedate
  hosts: all
  become: yes
  become_method: sudo
  collections:
    - name: community.general  
  #collections:
  #- name: community.general
  tasks:
  - name: Cau hinh timezone Asia/Ho_Chi_Minh
    community.general.timezone:
      name: Asia/Ho_Chi_Minh
