---
- name: Tao vm - ip tren netbox
  hosts: localhost
  gather_facts: true
  connection: local

  tasks:
    - name: Sending an e-mail html fomat
      community.general.mail:
        host: mail.smtp2go.com
        port: 2525
        username: "{{email_basic_username}}"
        password: "{{email_basic_password}}"
        from: admin@vlphere.com
        to: tcvn1985@gmail.com
        subject: Ansible-report {{ ansible_date_time.date}} tuan thu {{ansible_date_time.weeknumber}}
        subtype: html
        body: "{{ lookup('file', 'report.html') }}"
        # body: System {{ ansible_hostname }} has been successfully provisioned.
      delegate_to: localhost